language: node_js
node_js:
  - "4.1"
node_js:
  - "4.1"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
notifications:
  email:
    on_success: never
    on_failure: change
